version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rohanwebid96dong
      POSTGRES_DB: go-crash-course
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: